apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: seleniuminfo
    name: seleniuminfo
  name: seleniuminfo
  namespace: management
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: seleniuminfo
    spec:
      containers:
        -
          image: joes88/automated-mobile-testing:seleniuminfo-1
          name: seleniuminfo
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            -
              containerPort: 80
              protocol: TCP
          env:
            - name: STORAGEACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: storageaccount
                  key: name
            - name: STORAGEACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: storageaccount
                  key: key
#todo: liveness probes
---
apiVersion: v1
kind: Service
metadata:
  name: seleniuminfo
  namespace: management
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: seleniuminfo
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: management
    name: management
  name: management
  namespace: management
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: management
    spec:
      containers:
        -
          image: joes88/automated-mobile-testing:management-1
          name: management
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            -
              containerPort: 80
              protocol: TCP
#todo: liveness probes
---
apiVersion: v1
kind: Service
metadata:
  name: management
  namespace: management
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: management
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: datalogger
  namespace: management
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: datalogger
            image: joes88/automated-mobile-testing:datalogger-1
            env:
              - name: CONNECTIONSTRINGS__Redis
                value: redis
              - name: SeleniumNodesUrl
                value: "http://seleniuminfo/api/nodes"
          restartPolicy: OnFailure
---
 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: management
   namespace: management
   labels:
     app: management
   annotations:
     nginx.ingress.kubernetes.io/auth-type: basic
     nginx.ingress.kubernetes.io/auth-secret: demo
     nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/rewrite-target: "/"
 spec:
   rules:
    - http:
       paths:
       - backend:
           serviceName: "management"
           servicePort: 80
         path: /management