# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android
pool:
  vmImage: 'windows-latest'

steps:
# Commented out for the demo - I don't want to have to wait for it to build
# - task: Gradle@2
#   displayName: 'Build Android App'
#   inputs:
#     workingDirectory: './demo/UiTestCalc/'
#     gradleWrapperFile: './demo/UiTestCalc/gradlew'
#     gradleOptions: '-Xmx3072m'
#     publishJUnitResults: false
#     testResultsFiles: '**/TEST-*.xml'
#     tasks: 'assembleDebug'
# - task: AzurePowerShell@4
#   displayName: 'Publish'
#   inputs:
#     azureSubscription: 'DEV_Retail and Logistics(55476028-cbd9-47a9-bbdd-04dd8b0406fd)'
#     ScriptType: 'FilePath'
#     ScriptPath: './demo/deploy.ps1'
#     ScriptArguments: '-buildnumber ($Build.BuildNumber) -src ($Build.SourcesDirectory)'
#     azurePowerShellVersion: 'LatestVersion'
- task: Npm@1
  displayName: 'Install NPM testing dependencies'
  inputs:
    command: 'install'
    workingDir: './se-test-client'
- task: Npm@1
  displayName: 'Run UI tests'
  inputs:
    command: 'custom'
    workingDir: './se-test-client'
    customCommand: 'run test'
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'