apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  namespace: selenium
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: joes88/selenium-api:0.8.1
        ports:
          - containerPort: 4444
        env:
          - name: "SE_OPTS"
            value: "-debug"
          - name: "IFXDB_HOST"
            value: "influxdb"
          - name: "IFXDB_DB"
            value: "selenium"
          - name: "IFXDB_USER"
            valueFrom:
                secretKeyRef:
                  name: influxdb-creds
                  key: INFLUXDB_USERNAME
          - name: "IFXDB_PASSWD"
            valueFrom:
                secretKeyRef:
                  name: influxdb-creds
                  key: INFLUXDB_PASSWORD
        # When doing parallel testing selenium needs lots of resources https://github.com/SeleniumHQ/docker-selenium/issues/695
        resources:
          limits:
            memory: "2000Mi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /grid/admin/Console/nodes #/wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 60
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  namespace: selenium
  labels:
    app: selenium-hub
spec:
  ports:
  - port: 4444
    targetPort: 4444
    name: hub
  selector:
    app: selenium-hub
  type: NodePort
  sessionAffinity: None
---
 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: selenium-hub-auth
   namespace: selenium
   labels:
     app: selenium-hub
   annotations:
     nginx.ingress.kubernetes.io/auth-type: basic
     nginx.ingress.kubernetes.io/auth-secret: demo
     nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
     nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
 spec:
   rules:
    - http:
       paths:
       - backend:
           serviceName: "selenium-hub"
           servicePort: 4444
         path: /
---
# For some reason selenium queries /wd/session using 'noAuthConfigUrl' - which is not authenticated. Something to do with the jsonwire protocol
 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: selenium-hub
   namespace: selenium
   labels:
     app: selenium-hub
   annotations:
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
     nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
 spec:
   rules:
    - http:
       paths:
       - backend:
           serviceName: "selenium-hub"
           servicePort: 4444
         path: /wd/hub/session