apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: selenium
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: influxdb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:  
      - envFrom:
        - secretRef:
            name: influxdb-creds
        env:
          - name: CREATE_DB_QUERY
            value: CREATE DATABASE $INFLUXDB_DB
        image: docker.io/influxdb:1.7.6 
        imagePullPolicy: IfNotPresent
        name: influxdb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: influxdb
        persistentVolumeClaim:
          claimName: influxdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: selenium
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: selenium
  labels:
    app: influxdb
spec:
  ports:
  - port: 8086
    targetPort: 8086
    name: influxdb
  selector:
    app: influxdb
  type: NodePort
  sessionAffinity: None
---
 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: influxdb
   namespace: selenium
   labels:
     app: influxdb
   annotations:
    #  nginx.ingress.kubernetes.io/auth-type: basic
    #  nginx.ingress.kubernetes.io/auth-secret: demo
    #  nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
     nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
     nginx.ingress.kubernetes.io/rewrite-target: "/"
 spec:
   rules:
    - http:
       paths:
       - backend:
           serviceName: "influxdb"
           servicePort: 8086
         path: /influxdb
---
# When setting this up production these secrets should be in a key vault
apiVersion: v1
data:
  INFLUXDB_DB: c2VsZW5pdW0=
  INFLUXDB_HOST: aW5mbHV4ZGI=
  INFLUXDB_PASSWORD: cm9vdA==
  INFLUXDB_USERNAME: cm9vdA==
kind: Secret
metadata:
  name: influxdb-creds
  namespace: selenium
type: Opaque