 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: selenium-hub-auth
   namespace: selenium
   labels:
     app: selenium-hub
   annotations:
     nginx.ingress.kubernetes.io/auth-type: basic
     nginx.ingress.kubernetes.io/auth-secret: demo
     nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
     nginx.ingress.kubernetes.io/ssl-redirect: "false" 
     nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
     nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
 spec:
   rules:
    - http:
       paths:
       - backend:
           serviceName: "selenium-hub"
           servicePort: 4444
         path: /
---
# For some reason selenium queries /wd/session using 'noAuthConfigUrl' - which is not authenticated. Something to do with the jsonwire protocol
 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: selenium-hub
   namespace: selenium
   labels:
     app: selenium-hub
   annotations:
     nginx.ingress.kubernetes.io/ssl-redirect: "false" 
     nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
     nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
 spec:
   rules:
    - http:
       paths:
       - backend:
           serviceName: "selenium-hub"
           servicePort: 4444
         path: /wd/hub/session