apiVersion: v1
kind: Service
metadata:
  name: lb-selenium-hub
  namespace: selenium
  labels:
    app: lb-selenium-hub
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 10.10.0.10
  selector:
    app: selenium-hub
  ports:
  - name: selenium
    port: 4444