apiVersion: v1
data:
  auth: ZGVtbzokYXByMSRDLzJKeE1MTyR1QzZuY1l0MTJBOXZ0WDdlcmxGa3Au
kind: Secret
metadata:
  creationTimestamp: 2019-05-27T20:32:14Z
  name: demo
  namespace: selenium
  resourceVersion: "1341145"
  selfLink: /api/v1/namespaces/selenium/secrets/demo
  uid: 8333c67a-80be-11e9-a5c9-02dcfb6f7685
type: Opaque
